#!/usr/bin/env ruby

require "didgood"

if ARGV.size == 0
    ARGV.push "install"
end

case ARGV[0]
when "test"
    unless File.exist?("dgd.didgood")
        raise "I don't see a dgd.didgood file in this directory!"
    end
    puts "Running didgood installer..."
    repo = DidGood::Repo.new
    repo.didgood_file("dgd.didgood")
    puts "Verified Goods packages: this looks likely correct."
when "install"
    unless File.exist?("dgd.didgood")
        raise "I don't see a dgd.didgood file in this directory!"
    end
    puts "Running didgood installer..."
    repo = DidGood::Repo.new
    repo.didgood_file("dgd.didgood")
    repo.assemble_app(".")
when "work"
    puts "Starting DGD server... (not yet)"
else
    raise "Unrecognised didgood command: #{ARGV[0].inspect}!"
end
