#!/usr/bin/env ruby

# Diff multiple Skotos-XML-format objects dumped from a
# SkotOS-or-similar game to find out what updates should
# be merged between them.

require "dgd-tools/skotos_xml_obj"

if ARGV.size == 1 && ["-h", "--help"].include?(ARGV[0])
    print <<HELP_INFO
skotos-xml-diff [options] file1 file2

OR

skotos-xml-diff [options] dir1 dir2

Options include:
  --merry-only           Only examine Merry scripts
  --ignore-whitespace    Ignore all whitespace changes
HELP_INFO
    exit
end

args = ARGV

if args.include?("--merry-only")
    SkotOS::XMLObject.merry_only = true
    args -= ["--merry-only"]
end

if args.include?("--ignore-whitespace")
    SkotOS::XMLObject.ignore_whitespace = true
    args -= ["--ignore-whitespace"]
end

if args.size != 2
    STDERR.puts "Usage: skotos-xml-diff [options] <obj_or_dir_1> <obj_or_dir_2>"
    exit -1
end

if File.directory?(args[0]) ^ File.directory?(args[1])
    STDERR.puts "Please give two files or two directories, not one of each!"
    exit -1
end

if File.directory?(args[0])
    diff = SkotOS::XMLObject.diff_dirs(*args)
    if diff.empty?
        puts "No difference."
    else
        puts diff.join("\n\n=====\n\n")
    end
else
    obj1 = SkotOS::XMLObject.from_file(args[0])
    obj2 = SkotOS::XMLObject.from_file(args[1])
    diff = SkotOS::XMLObject.diff_between(obj1, obj2)
    if diff.empty?
        puts "No difference."
    else
        puts diff
    end
end
